import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { toast, Toaster } from "@/components/ui/sonner";
import { Copy, Download, Redo2, Undo2, Share2, Play, GitBranch, Settings2 } from "lucide-react";
import { SandpackProvider, SandpackLayout, SandpackPreview, SandpackCodeEditor } from "@codesandbox/sandpack-react";
import { compressToEncodedURIComponent, decompressFromEncodedURIComponent } from "lz-string";
import JSZip from "jszip";

// ---------------- Types ----------------
export type IR = {
  pages: Array<{ name: string; path: string; type: "landing" | "login" | "dashboard" | "custom"; widgets?: string[] }>;
  models: Array<{ name: string; fields: Array<{ name: string; type: string; optional?: boolean }> }>;
  auth: { type: "jwt" | "oauth"; providers?: string[] };
  apis: Array<{ method: "GET" | "POST" | "PUT" | "DELETE"; route: string; model?: string; action?: string }>;
  notes?: string[]; // assumptions
};

export type Project = {
  command: string;
  ir: IR;
  frontend: Record<string, string>; // file path -> contents
  backend: Record<string, string>; // nextjs app router files
  prisma: string;
};

// ---------------- Parser ----------------
function parseCommand(command: string): IR {
  const lower = command.toLowerCase();
  const pages: IR["pages"] = [];
  if (/(landing|home|marketing)/.test(lower)) pages.push({ name: "Home", path: "/", type: "landing" });
  if (/login|auth/.test(lower)) pages.push({ name: "Login", path: "/login", type: "login" });
  if (/dashboard/.test(lower)) pages.push({ name: "Dashboard", path: "/dashboard", type: "dashboard" });
  if (pages.length === 0) pages.push({ name: "Home", path: "/", type: "custom", widgets: ["hero", "cta"] });

  const models: IR["models"] = [];
  if (/user/.test(lower) || /auth/.test(lower)) {
    models.push({
      name: "User",
      fields: [
        { name: "id", type: "String" },
        { name: "email", type: "String" },
        { name: "passwordHash", type: "String" },
        { name: "createdAt", type: "DateTime" },
      ],
    });
  }
  if (/todo|task/.test(lower)) {
    models.push({
      name: "Task",
      fields: [
        { name: "id", type: "String" },
        { name: "title", type: "String" },
        { name: "completed", type: "Boolean" },
        { name: "userId", type: "String" },
      ],
    });
  }

  const auth: IR["auth"] = /oauth/.test(lower)
    ? { type: "oauth", providers: ["github"] }
    : { type: "jwt" };

  const apis: IR["apis"] = [];
  // Basic CRUD APIs for detected models
  for (const m of models) {
    apis.push({ method: "GET", route: `/api/${m.name.toLowerCase()}s`, model: m.name, action: "list" });
    apis.push({ method: "POST", route: `/api/${m.name.toLowerCase()}s`, model: m.name, action: "create" });
  }
  if (auth.type === "jwt") {
    apis.push({ method: "POST", route: "/api/auth/login", action: "login" });
    apis.push({ method: "POST", route: "/api/auth/register", action: "register" });
  }

  const notes: string[] = [];
  if (!/db|prisma|postgres/.test(lower)) notes.push("Assumption: Using Prisma + Postgres for persistence.");
  if (!/auth/.test(lower)) notes.push("Assumption: JWT auth by default.");

  return { pages, models, auth, apis, notes };
}

// ---------------- Generators ----------------
function genPrisma(ir: IR) {
  const base = `// Prisma schema generated by Loveable\n// Assumption: Using PostgreSQL\n// Set DATABASE_URL in .env before running\n\n datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n }\n\n generator client {\n  provider = "prisma-client-js"\n }\n`;

  const models = ir.models.length
    ? ir.models
        .map((m) => {
          const fields = m.fields
            .map((f) => {
              const type = f.type === "DateTime" ? "DateTime" : f.type;
              const id = f.name === "id" ? " @id @default(cuid())" : "";
              return `  ${f.name} ${type}${f.optional ? "?" : ""}${id}`;
            })
            .join("\n");
          return `\nmodel ${m.name} {\n${fields}\n}`;
        })
        .join("\n")
    : `\nmodel User {\n  id          String   @id @default(cuid())\n  email       String   @unique\n  passwordHash String\n  createdAt   DateTime @default(now())\n}`;

  return base + models + "\n";
}

function genFrontendFiles(ir: IR): Record<string, string> {
  const indexHtml = `<!doctype html>\n<html>\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <title>Loveable Preview</title>\n    <!-- Tailwind via CDN for preview only -->\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body class=\"bg-neutral-950 text-white\">\n    <div id=\"root\"></div>\n    <script type=\"module\" src=\"/src/main.tsx\"></script>\n  </body>\n</html>`;

  const mainTsx = `import React from 'react'\nimport { createRoot } from 'react-dom/client'\nimport App from './App'\ncreateRoot(document.getElementById('root')!).render(<App />)`;

  // Basic router
  const appTsx = `import React from 'react'\nimport { useState } from 'react'\n\nfunction Nav({ routes, setRoute, route }) {\n  return (<nav className=\"sticky top-0 backdrop-blur border-b border-white/10 px-4 py-3 flex gap-4\">\n    {routes.map(r => <a key={r.path} href={r.path} onClick={(e)=>{e.preventDefault(); setRoute(r.path)}} className={\"text-sm hover:text-teal-300 \" + (route===r.path? 'text-teal-300':'text-white')}>{r.name}</a>)}\n  </nav>)\n}\n\nexport default function App(){\n  const routes = ${JSON.stringify(ir.pages)};\n  const [route, setRoute] = useState(routes[0]?.path || '/')\n  return (<div>\n    <Nav routes={routes} setRoute={setRoute} route={route} />\n    <main className=\"p-6 space-y-6\">\n      {route==='/' && (<section>\n        <h1 className=\"text-4xl font-bold bg-gradient-to-r from-rose-400 to-teal-300 text-transparent bg-clip-text\">Welcome to Loveable</h1>\n        <p className=\"text-neutral-400 mt-2\">This preview is generated from your command.</p>\n      </section>)}\n      ${ir.pages
        .filter((p) => p.path !== "/")
        .map((p) => {
          if (p.type === "login") {
            return `route==='${p.path}' && (<section className=\"max-w-sm\">\n  <h2 className=\"text-2xl font-semibold mb-4\">Login</h2>\n  <form className=\"space-y-3\">\n    <input className=\"w-full rounded border border-white/10 bg-white/5 px-3 py-2\" placeholder=\"Email\"/>\n    <input type=\"password\" className=\"w-full rounded border border-white/10 bg-white/5 px-3 py-2\" placeholder=\"Password\"/>\n    <button className=\"w-full rounded bg-gradient-to-r from-rose-400 to-teal-300 px-3 py-2 text-black font-semibold\">Sign in</button>\n  </form>\n</section>)`;
          }
          if (p.type === "dashboard") {
            return `route==='${p.path}' && (<section>\n  <h2 className=\"text-2xl font-semibold\">Dashboard</h2>\n  <div className=\"grid grid-cols-1 md:grid-cols-3 gap-4 mt-4\">\n    <div className=\"rounded-xl border border-white/10 p-4\">Users <span className=\"text-teal-300\">42</span></div>\n    <div className=\"rounded-xl border border-white/10 p-4\">Tasks <span className=\"text-teal-300\">128</span></div>\n    <div className=\"rounded-xl border border-white/10 p-4\">Revenue <span className=\"text-teal-300\">$5.2k</span></div>\n  </div>\n</section>)`;
          }
          return `route==='${p.path}' && (<section><h2 className=\"text-2xl font-semibold\">${p.name}</h2><p className=\"text-neutral-400\">Generated page.</p></section>)`;
        })
        .join("\n      ")}
    </main>\n  </div>)\n}`;

  return {
    "/index.html": indexHtml,
    "/src/main.tsx": mainTsx,
    "/src/App.tsx": appTsx,
  };
}

function genNextApiFiles(ir: IR): Record<string, string> {
  const files: Record<string, string> = {};
  // Basic app router structure
  files["/app/page.tsx"] = `export default function Home(){ return <main>Loveable App</main> }`;
  files["/package.json"] = `{
  "name": "loveable-app",
  "private": true,
  "scripts": { "dev": "next dev", "build": "next build", "start": "next start" },
  "dependencies": { "next": "14.2.10", "react": "19.0.0", "react-dom": "19.0.0", "prisma": "^5.16.1", "@prisma/client": "^5.16.1", "jsonwebtoken": "^9.0.2", "bcryptjs": "^2.4.3" }
}`;
  files["/tsconfig.json"] = `{
  "compilerOptions": { "strict": true, "jsx": "preserve", "module": "esnext", "target": "es2022", "moduleResolution": "bundler", "baseUrl": "." },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}`;
  files["/next.config.js"] = `/** @type {import('next').NextConfig} */\nmodule.exports = { experimental: { serverActions: true } }`;
  files["/.env.example"] = `# Required: set the Postgres connection URL\nDATABASE_URL=postgresql://user:pass@host:5432/db\n# JWT secret for signing tokens\nJWT_SECRET=change-me`;
  files["/prisma/schema.prisma"] = genPrisma(ir);

  // Auth routes
  files["/app/api/auth/login/route.ts"] = `import { NextRequest, NextResponse } from 'next/server'\nimport jwt from 'jsonwebtoken'\nimport bcrypt from 'bcryptjs'\nimport { PrismaClient } from '@prisma/client'\nconst prisma = new PrismaClient()\nexport async function POST(req: NextRequest){\n  const { email, password } = await req.json()\n  // In production add rate-limit and validation\n  const user = await prisma.user.findUnique({ where: { email } })\n  if(!user || !bcrypt.compareSync(password, user.passwordHash)) return NextResponse.json({ error: 'Invalid credentials' }, { status: 401 })\n  const token = jwt.sign({ sub: user.id, email }, process.env.JWT_SECRET!, { expiresIn: '1d' })\n  return NextResponse.json({ token })\n}`;

  files["/app/api/auth/register/route.ts"] = `import { NextRequest, NextResponse } from 'next/server'\nimport bcrypt from 'bcryptjs'\nimport { PrismaClient } from '@prisma/client'\nconst prisma = new PrismaClient()\nexport async function POST(req: NextRequest){\n  const { email, password } = await req.json()\n  const existing = await prisma.user.findUnique({ where: { email } })\n  if(existing) return NextResponse.json({ error: 'Email taken' }, { status: 409 })\n  const passwordHash = bcrypt.hashSync(password, 10)\n  const user = await prisma.user.create({ data: { email, passwordHash } })\n  return NextResponse.json({ id: user.id, email: user.email })\n}`;

  // CRUD routes for models
  for (const m of ir.models) {
    const base = m.name.toLowerCase() + "s";
    files[`/app/api/${base}/route.ts`] = `import { NextRequest, NextResponse } from 'next/server'\nimport { PrismaClient } from '@prisma/client'\nconst prisma = new PrismaClient()\nexport async function GET(){ const data = await prisma.${base}.findMany(); return NextResponse.json(data) }\nexport async function POST(req: NextRequest){ const body = await req.json(); const created = await prisma.${base}.create({ data: body }); return NextResponse.json(created,{ status: 201 }) }`;
  }

  return files;
}

// ---------------- Utilities ----------------
function buildProject(command: string): Project {
  const ir = parseCommand(command);
  const frontend = genFrontendFiles(ir);
  const backend = genNextApiFiles(ir);
  const prisma = backend["/prisma/schema.prisma"]; // same
  return { command, ir, frontend, backend, prisma };
}

function useHistory<T>(initial: T) {
  const [past, setPast] = useState<T[]>([]);
  const [present, setPresent] = useState<T>(initial);
  const [future, setFuture] = useState<T[]>([]);
  return {
    state: present,
    canUndo: past.length > 0,
    canRedo: future.length > 0,
    set: (next: T) => {
      setPast((p) => [...p, present]);
      setPresent(next);
      setFuture([]);
    },
    undo: () => {
      if (!past.length) return;
      const prev = past[past.length - 1];
      setPast((p) => p.slice(0, -1));
      setFuture((f) => [present, ...f]);
      setPresent(prev);
    },
    redo: () => {
      if (!future.length) return;
      const next = future[0];
      setFuture((f) => f.slice(1));
      setPast((p) => [...p, present]);
      setPresent(next);
    },
  };
}

function asSandpackFiles(frontend: Record<string, string>) {
  // Sandpack expects object without leading slash
  const files: Record<string, { code: string }> = {};
  Object.entries(frontend).forEach(([path, code]) => {
    files[path.replace(/^\//, "")] = { code };
  });
  return files;
}

function downloadZip(project: Project) {
  const zip = new JSZip();
  const frontend = zip.folder("frontend")!;
  const backend = zip.folder("backend-nextjs")!;
  Object.entries(project.frontend).forEach(([p, c]) => frontend.file(p.replace(/^\//, ""), c));
  Object.entries(project.backend).forEach(([p, c]) => backend.file(p.replace(/^\//, ""), c));
  zip.file("README.md", `# Loveable Generated Project\n\n## Frontend (preview)\n- React + Tailwind (CDN for preview)\n\n## Backend\n- Next.js App Router\n- Prisma + PostgreSQL\n- JWT Auth endpoints\n\n### Setup\n1. Copy backend-nextjs to a new repo, run \`npm i\`\n2. Set \`.env\` from \`.env.example\` (DATABASE_URL, JWT_SECRET)\n3. Run \`npx prisma migrate dev\`\n4. \`npm run dev\` or deploy to Vercel\n`);
  zip.generateAsync({ type: "blob" }).then((blob) => {
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "loveable-project.zip";
    a.click();
    URL.revokeObjectURL(a.href);
  });
}

// ---------------- UI ----------------
export default function Builder() {
  const [input, setInput] = useState("build login page with Tailwind and JWT auth, add dashboard with task list");
  const history = useHistory<Project>(buildProject(input));

  // live preview update when input changes
  useEffect(() => {
    const id = setTimeout(() => {
      history.set(buildProject(input));
    }, 400);
    return () => clearTimeout(id);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [input]);

  useEffect(() => {
    // restore from URL if present
    const hash = location.hash.replace(/^#/, "");
    if (hash) {
      try {
        const json = decompressFromEncodedURIComponent(hash);
        if (json) {
          const proj = JSON.parse(json) as Project;
          setInput(proj.command);
          history.set(proj);
        }
      } catch {}
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const share = () => {
    const encoded = compressToEncodedURIComponent(JSON.stringify(history.state));
    const url = `${location.origin}/builder#${encoded}`;
    navigator.clipboard.writeText(url);
    toast("Share link copied to clipboard");
  };

  const files = useMemo(() => asSandpackFiles(history.state.frontend), [history.state.frontend]);

  return (
    <div className="mx-auto max-w-[1200px] px-4 py-8">
      <Toaster />
      <h1 className="text-3xl font-bold gradient-text">Loveable Builder</h1>
      <p className="text-muted-foreground mt-1">Type a command. We'll interpret it, generate code, and live-preview the UI. Backend/API and Prisma schema are generated too.</p>

      <Card className="mt-6 p-4">
        <div className="flex flex-col gap-3 md:flex-row md:items-center">
          <Textarea value={input} onChange={(e)=>setInput(e.target.value)} className="min-h-20" placeholder="e.g. build login page with Tailwind and JWT auth" />
          <div className="flex gap-2 md:self-start">
            <Button onClick={()=>history.set(buildProject(input))}><Play className="mr-2 h-4 w-4"/>Build</Button>
            <Button variant="outline" onClick={history.undo} disabled={!history.canUndo}><Undo2 className="mr-2 h-4 w-4"/>Undo</Button>
            <Button variant="outline" onClick={history.redo} disabled={!history.canRedo}><Redo2 className="mr-2 h-4 w-4"/>Redo</Button>
            <Button variant="outline" onClick={share}><Share2 className="mr-2 h-4 w-4"/>Share</Button>
            <Button variant="outline" onClick={()=>downloadZip(history.state)}><Download className="mr-2 h-4 w-4"/>Download</Button>
          </div>
        </div>
        <div className="mt-2 flex flex-wrap items-center gap-2">
          <Badge variant="secondary">Auth: {history.state.ir.auth.type.toUpperCase()}</Badge>
          <Badge variant="secondary">Pages: {history.state.ir.pages.length}</Badge>
          <Badge variant="secondary">Models: {history.state.ir.models.length}</Badge>
        </div>
      </Card>

      <Tabs defaultValue="preview" className="mt-6">
        <TabsList>
          <TabsTrigger value="preview">Preview</TabsTrigger>
          <TabsTrigger value="frontend">Frontend Files</TabsTrigger>
          <TabsTrigger value="api">API Routes</TabsTrigger>
          <TabsTrigger value="prisma">Prisma Schema</TabsTrigger>
          <TabsTrigger value="ir">IR</TabsTrigger>
        </TabsList>
        <TabsContent value="preview" className="mt-4">
          <SandpackProvider files={files} template="vite-react-ts" options={{ recompileMode: "immediate" }}>
            <SandpackLayout>
              <SandpackPreview className="rounded-lg border" />
              <SandpackCodeEditor showTabs wrapContent style={{ height: 400 }} />
            </SandpackLayout>
          </SandpackProvider>
        </TabsContent>
        <TabsContent value="frontend" className="mt-4">
          <CodeList files={history.state.frontend} />
        </TabsContent>
        <TabsContent value="api" className="mt-4">
          <CodeList files={history.state.backend} />
        </TabsContent>
        <TabsContent value="prisma" className="mt-4">
          <pre className="rounded-lg border bg-black/50 p-4 text-xs text-white/90 overflow-auto"><code>{history.state.prisma}</code></pre>
        </TabsContent>
        <TabsContent value="ir" className="mt-4">
          <pre className="rounded-lg border bg-black/50 p-4 text-xs text-white/90 overflow-auto"><code>{JSON.stringify(history.state.ir, null, 2)}</code></pre>
        </TabsContent>
      </Tabs>

      <div className="mt-8 text-sm text-muted-foreground">
        <p>Notes/assumptions:</p>
        <ul className="list-disc pl-5">
          {history.state.ir.notes?.map((n)=> <li key={n}>{n}</li>)}
        </ul>
      </div>
    </div>
  );
}

function CodeList({ files }: { files: Record<string, string> }){
  return (
    <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
      {Object.entries(files).map(([path, code]) => (
        <Card key={path} className="overflow-hidden">
          <div className="flex items-center justify-between border-b px-4 py-2 text-xs">
            <span className="text-muted-foreground">{path}</span>
            <Button variant="ghost" size="sm" onClick={()=>{navigator.clipboard.writeText(code)}}><Copy className="h-4 w-4"/></Button>
          </div>
          <pre className="max-h-80 overflow-auto bg-black/50 p-4 text-xs text-white/90"><code>{code}</code></pre>
        </Card>
      ))}
    </div>
  );
}